# GET http://localhost:8000/api/v1/products

# # # ###
# POST http://localhost:8000/api/v1/products/create
# Content-Type: application/json

# {
#     "name":"Laptop",
#     "quantity":9
# }
 

# DELETE http://localhost:8000/api/v1/products/64313fe8783df1ec049618ec

# PATCH  http://localhost:8000/api/v1/products/6431404f2896f91aa604e8eb/update_quantity/?number=10